<?php

return [
            [
                '选课',
                '/course/explore',
                [
                    ['签约套餐班','/classroom/explore',FALSE],
                    ['私塾直播课','/online',FALSE],
                    ['留学日语','course/explore/jap',FALSE],
                    ['留考校内考','/course/explore/eju_zhuan',FALSE],
                    ['艺术留学课程','/course/explore/art',FALSE],
                    ['院生考试','/course/explore/yuan',FALSE],
                    ['全部课程','/course/explore',FALSE],
                ]
            ],
            [
                '留学方案',
                '/plan',
                FALSE,
            ],
            [
                '日本读研',
                '/duyan',
                [
                    ['TOP10院生直考签约','/yuan',FALSE],
                    ['SGU/G30英语项目直申','/sgu',FALSE],
                    ['日本读研集训营全国高校巡讲','/article/1657',FALSE],
                    ['读研申请服务','/duyan',FALSE],
                ]
            ],
            [
                '院校库',
                '/school',
                [
                    ['日本大学排名','/rank',FALSE],
                    ['语言学校排名','/rank/2',FALSE],
                ]
            ],
            [
                '案例中心',
                '/case',
                [
                    ['全部案例','/case',FALSE],
                    ['录取证书','/cases',FALSE],
                ]
            ],
            [
                '名师',
                '/teacher',
                FALSE
            ],
            [
                '公开课',
                '/college',
                FALSE
            ],
       ];